version: '3.8'

services:
  app:
    image: php:8.2-fpm
    container_name: php_app
    restart: always
    volumes:
      - ./backend:/var/www/html
    environment:
      - DB_HOST=db
      - DB_DATABASE=${MYSQL_DATABASE}
      - DB_USERNAME=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
    depends_on:
      - db

  web:
    image: nginx:latest
    container_name: nginx_web
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./Frontend/dist:/usr/share/nginx/html  # Vue静态文件
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: mysql:8
    container_name: mysql_db
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
